//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnacioDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clases()
        {
            this.MiembrosClases = new HashSet<MiembrosClases>();
        }
    
        public int IdClase { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cupoMaximo { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> IdEntrenador { get; set; }
        public string tipo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiembrosClases> MiembrosClases { get; set; }
    }
}
