//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnacioDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GimnacioEntities : DbContext
    {
        public GimnacioEntities()
            : base("name=GimnacioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clases> Clases { get; set; }
        public virtual DbSet<Membresias> Membresias { get; set; }
        public virtual DbSet<Miembros> Miembros { get; set; }
        public virtual DbSet<MiembrosClases> MiembrosClases { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
