//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnacioDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miembros()
        {
            this.MiembrosClases = new HashSet<MiembrosClases>();
            this.Pagos = new HashSet<Pagos>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdMiembro { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<int> IdMembresia { get; set; }
    
        public virtual Membresias Membresias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiembrosClases> MiembrosClases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
