//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnacioDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiembrosClases
    {
        public int IdMiembroClase { get; set; }
        public Nullable<int> IdMiembro { get; set; }
        public Nullable<int> IdClase { get; set; }
    
        public virtual Clases Clases { get; set; }
        public virtual Miembros Miembros { get; set; }
    }
}
