//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnacioDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int IdPago { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string motivo { get; set; }
        public Nullable<int> IdMiembro { get; set; }
    
        public virtual Miembros Miembros { get; set; }
    }
}
